# Test binary executable files from kotlin multiplataform build

name: 'test-binary-executables-kotlin-multiplataform'

on: 
  workflow_dispatch:
  pull_request:
    branches:
      - "main"
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        include:
          - os: ubuntu-latest
            target: linuxX64 
            extension: 'katan-cli.kexe'

          - os: macos-latest
            target: macosX64
            extension: 'katan-cli.kexe'

          - os: windows-latest
            target: mingwX64
            extension: 'katan-cli.exe'
    steps:
      - uses: actions/checkout@v2.3.4

      - name: Build katan-cli project (${{matrix.target}})
        uses: burrunan/gradle-cache-action@v1
        with:
          job-id: ${{matrix.target}}
          arguments: clean install
          gradle-version: wrapper

      #- name: Show all the bundled binary files
      #  run: |
      #    find ./build -name "katan-cli*"

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{github.run_id}}
          release_name: "Katan-cli release"
          draft: false
          prerelease: false

      - name: Upload binaries
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: build/bin/${{ matrix.target }}/debugExecutable/${{matrix.extension}}
          asset_name: ${{ matrix.target }}
          asset_content_type: application/octet-stream